spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://${MARIADB_URL}
      username: ${MARIADB_USERNAME}
      password: ${MARIADB_PASSWORD}
      driver-class-name: org.mariadb.jdbc.Driver
      minimum-idle: 5
      idle-timeout: 60000
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    open-in-view: false
    hibernate:
      ddl-auto: none

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

logging:
  level:
    org.hibernate.SQL: DEBUG #Hibernate SQL ??
    org.hibernate.orm.jdbc.bind: TRACE # ??? ????
    org.hibernate.orm.jdbc.extract: TRACE # ?? ??

jwt:
  secret-key: ${JWT_SECRET_KEY}

file:
  save:
    url: ${FILE_SAVE_URL}
  company:
    url: company/
  portfolio:
    url: portfolio/

server:
  port: 8090
